require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MonthliesController do

  # This should return the minimal set of attributes required to create a valid
  # Monthly. As you add validations to Monthly, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MonthliesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all monthlies as @monthlies" do
      monthly = Monthly.create! valid_attributes
      get :index, {}, valid_session
      assigns(:monthlies).should eq([monthly])
    end
  end

  describe "GET show" do
    it "assigns the requested monthly as @monthly" do
      monthly = Monthly.create! valid_attributes
      get :show, {:id => monthly.to_param}, valid_session
      assigns(:monthly).should eq(monthly)
    end
  end

  describe "GET new" do
    it "assigns a new monthly as @monthly" do
      get :new, {}, valid_session
      assigns(:monthly).should be_a_new(Monthly)
    end
  end

  describe "GET edit" do
    it "assigns the requested monthly as @monthly" do
      monthly = Monthly.create! valid_attributes
      get :edit, {:id => monthly.to_param}, valid_session
      assigns(:monthly).should eq(monthly)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Monthly" do
        expect {
          post :create, {:monthly => valid_attributes}, valid_session
        }.to change(Monthly, :count).by(1)
      end

      it "assigns a newly created monthly as @monthly" do
        post :create, {:monthly => valid_attributes}, valid_session
        assigns(:monthly).should be_a(Monthly)
        assigns(:monthly).should be_persisted
      end

      it "redirects to the created monthly" do
        post :create, {:monthly => valid_attributes}, valid_session
        response.should redirect_to(Monthly.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved monthly as @monthly" do
        # Trigger the behavior that occurs when invalid params are submitted
        Monthly.any_instance.stub(:save).and_return(false)
        post :create, {:monthly => { "user" => "invalid value" }}, valid_session
        assigns(:monthly).should be_a_new(Monthly)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Monthly.any_instance.stub(:save).and_return(false)
        post :create, {:monthly => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested monthly" do
        monthly = Monthly.create! valid_attributes
        # Assuming there are no other monthlies in the database, this
        # specifies that the Monthly created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Monthly.any_instance.should_receive(:update_attributes).with({ "user" => "" })
        put :update, {:id => monthly.to_param, :monthly => { "user" => "" }}, valid_session
      end

      it "assigns the requested monthly as @monthly" do
        monthly = Monthly.create! valid_attributes
        put :update, {:id => monthly.to_param, :monthly => valid_attributes}, valid_session
        assigns(:monthly).should eq(monthly)
      end

      it "redirects to the monthly" do
        monthly = Monthly.create! valid_attributes
        put :update, {:id => monthly.to_param, :monthly => valid_attributes}, valid_session
        response.should redirect_to(monthly)
      end
    end

    describe "with invalid params" do
      it "assigns the monthly as @monthly" do
        monthly = Monthly.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Monthly.any_instance.stub(:save).and_return(false)
        put :update, {:id => monthly.to_param, :monthly => { "user" => "invalid value" }}, valid_session
        assigns(:monthly).should eq(monthly)
      end

      it "re-renders the 'edit' template" do
        monthly = Monthly.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Monthly.any_instance.stub(:save).and_return(false)
        put :update, {:id => monthly.to_param, :monthly => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested monthly" do
      monthly = Monthly.create! valid_attributes
      expect {
        delete :destroy, {:id => monthly.to_param}, valid_session
      }.to change(Monthly, :count).by(-1)
    end

    it "redirects to the monthlies list" do
      monthly = Monthly.create! valid_attributes
      delete :destroy, {:id => monthly.to_param}, valid_session
      response.should redirect_to(monthlies_url)
    end
  end

end
